from PyQt5.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QLabel, QFrame
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import Qt, pyqtSignal

class CanvasWidget(QWidget):
    """
    A dedicated preview environment for rendering artifacts like HTML, SVG, 
    and UI components generated by the AI.
    """
    closed = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._setup_ui()
        self._last_content = ""

    def _setup_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        # Header
        self.header = QFrame()
        self.header.setFixedHeight(35)
        self.header.setStyleSheet("background-color: #2d2d2d; border-bottom: 1px solid #3e3e3e;")
        header_layout = QHBoxLayout(self.header)
        header_layout.setContentsMargins(10, 0, 10, 0)

        self.title_label = QLabel("Canvas Preview")
        self.title_label.setStyleSheet("font-weight: bold; color: #cccccc;")
        header_layout.addWidget(self.title_label)
        header_layout.addStretch()

        self.refresh_btn = QPushButton("Refresh")
        self.refresh_btn.setFixedWidth(70)
        self.refresh_btn.setStyleSheet("background: #3e3e3e; border: none; border-radius: 4px; color: #fff; padding: 2px;")
        self.refresh_btn.clicked.connect(self.refresh)
        header_layout.addWidget(self.refresh_btn)

        layout.addWidget(self.header)

        # Web View
        self.view = QWebEngineView()
        self.view.setStyleSheet("background: #ffffff;") # Clear background for previews
        layout.addWidget(self.view)

    def set_content(self, html, title="Canvas Preview"):
        self._last_content = html
        self.title_label.setText(title)
        
        # Ensure it has a base structure if it's just a fragment
        if "<html" not in html.lower():
            # Wrap in a standard container with some nice defaults (Inter font, etc)
            full_html = f"""
            <!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8">
                <style>
                    body {{
                        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                        margin: 20px;
                        background-color: white;
                        color: black;
                    }}
                </style>
            </head>
            <body>
                {html}
            </body>
            </html>
            """
            self.view.setHtml(full_html)
        else:
            self.view.setHtml(html)

    def refresh(self):
        if self._last_content:
            self.set_content(self._last_content, self.title_label.text())

    def clear(self):
        self._last_content = ""
        self.view.setHtml("<html><body><p style='color:#888; text-align:center; margin-top:100px;'>No preview active</p></body></html>")
