from PyQt5.QtWidgets import QWidget, QVBoxLayout, QHBoxLayout, QPushButton, QLabel, QFrame
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineSettings
from PyQt5.QtCore import Qt, pyqtSignal, QUrl
import logging
import tempfile
import webbrowser
import os

log = logging.getLogger(__name__)

class CanvasWidget(QWidget):
    """
    A dedicated preview environment for rendering artifacts like HTML, SVG, 
    and UI components generated by the AI.
    """
    closed = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._setup_ui()
        self._last_content = ""
        self._last_type = "html"

    def _setup_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)

        # Header
        self.header = QFrame()
        self.header.setFixedHeight(35)
        self.header.setStyleSheet("background-color: #2d2d2d; border-bottom: 1px solid #3e3e3e;")
        header_layout = QHBoxLayout(self.header)
        header_layout.setContentsMargins(12, 0, 8, 0)

        self.title_label = QLabel("Canvas Preview")
        self.title_label.setStyleSheet("font-weight: bold; color: #cccccc; font-size: 12px;")
        header_layout.addWidget(self.title_label)
        
        header_layout.addStretch()

        self.browser_btn = QPushButton("\ud83c\udf10") # Globe
        self.browser_btn.setToolTip("Open in Browser")
        self.browser_btn.setFixedSize(26, 26)
        self.browser_btn.setStyleSheet("QPushButton { background: transparent; border: none; font-size: 13px; } QPushButton:hover { background: #3c3c3c; }")
        self.browser_btn.clicked.connect(self._open_in_browser)
        header_layout.addWidget(self.browser_btn)

        self.refresh_btn = QPushButton("\u21bb") # Refresh
        self.refresh_btn.setToolTip("Refresh")
        self.refresh_btn.setFixedSize(26, 26)
        self.refresh_btn.setStyleSheet("QPushButton { background: transparent; border: none; font-size: 13px; } QPushButton:hover { background: #3c3c3c; }")
        self.refresh_btn.clicked.connect(self.refresh)
        header_layout.addWidget(self.refresh_btn)

        layout.addWidget(self.header)

        # Web View
        self.view = QWebEngineView()
        self.view.settings().setAttribute(QWebEngineSettings.LocalContentCanAccessRemoteUrls, True)
        self.view.settings().setAttribute(QWebEngineSettings.JavascriptEnabled, True)
        self.view.setStyleSheet("background: #ffffff;") 
        layout.addWidget(self.view)

    def set_content(self, content, title="Canvas Preview", content_type="html"):
        self._last_content = content
        self._last_type = content_type
        self.title_label.setText(title)
        
        if content_type.lower() == 'svg':
            html = f"<html><body style='background:#f0f0f0; display:flex; justify-content:center; align-items:center; height:100vh; margin:0;'>{content}</body></html>"
            self.view.setHtml(html)
        elif content_type.lower() == 'mermaid':
            html = f"""
            <html>
            <head>
                <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
                <style>body {{ background: #1e1e1e; color: white; display: flex; justify-content: center; padding: 20px; }}</style>
            </head>
            <body>
                <div class="mermaid">{content}</div>
                <script>mermaid.initialize({{ startOnLoad: true, theme: 'dark' }});</script>
            </body>
            </html>
            """
            self.view.setHtml(html)
        else:
            # Assume HTML
            if "<html" not in content.lower() and "<body" not in content.lower():
                full_html = f"<!DOCTYPE html><html><body style='font-family:sans-serif; margin:20px;'>{content}</body></html>"
                self.view.setHtml(full_html)
            else:
                self.view.setHtml(content)

    def refresh(self):
        if self._last_content:
            self.set_content(self._last_content, self.title_label.text(), self._last_type)

    def _open_in_browser(self):
        if not self._last_content: return
        suffix = ".html"
        if self._last_type == 'svg': suffix = ".svg"
        with tempfile.NamedTemporaryFile(delete=False, suffix=suffix) as f:
            f.write(self._last_content.encode('utf-8'))
            temp_path = f.name
        webbrowser.open(f"file://{os.path.abspath(temp_path)}")

    def clear(self):
        self._last_content = ""
        self.view.setHtml("<html><body style='background:#1e1e1e; color:#888; display:flex; justify-content:center; align-items:center; height:100vh;'>No preview active</body></html>")

    def apply_theme(self, theme):
        bg = theme.get("sidebar_bg", "#2d2d2d")
        border = theme.get("border", "#3e3e3e")
        fg = theme.get("fg", "#cccccc")
        self.header.setStyleSheet(f"background-color: {bg}; border-bottom: 1px solid {border};")
        self.title_label.setStyleSheet(f"font-weight: bold; color: {fg}; font-size: 12px;")
